mongodb_data:
    image:
        neogeo/docker-mongodb-client
    volumes:
        - /data/db
        - /data/log
    command:
        echo "MongoDB /data/db and data/log"
mongodb_server:
    image:
        neogeo/docker-mongodb-server
    volumes_from:
        - mongodb_data
    ports:
        - "27017:27017"